### ISSUE TITLE
Feedback for First Model/Views

### ISSUE THREAD

**Issue by rplugge** [rplugge/sinatra_trains#10]

**Comment by sumeetjain** [comment]
- [x] Does not follow project folder structure
- [x] Module is not being used
- [x] Views are missing

**Comment by sumeetjain** [comment]
- [x] Should not be `puts` statements anywhere. Handle display of information using ERB in views.

**Comment by sumeetjain** [comment]
- [ ] Need to specify what kind of data each parameter takes. E.g. [this](https://github.com/rplugge/sinatra_trains/blob/master/class_methods.rb#L26-L38) method is missing what kind of data `id` is.
- [ ] Can you write an _instance_ method (doesn't have to be in the module – in the model itself is fine) that adds a given object to the database as a new row? Basically can `TheClass.add({"attribute1" => params["a1"], "attribute2" => params["a2"]})` be replaced by `@an_object.add_to_database`? (https://github.com/rplugge/sinatra_trains/blob/master/controllers/trains.rb#L8)
